name: CML
on:
  push:
    branches:
      - dev
  pull_request:
      branches:
        - main
permissions:
  contents: write
  pull-requests: write

jobs:
  test-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -v > test_output.txt 2>&1

      - name: Create cml report
        run: |
          echo "Test Report" >> report.md
          echo "-" >> report.md
          cat test_output.txt >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
