name: CML
on:
  push:
    branches:
      - dev
  pull_request:
      branches:
        - main
permissions:
  contents: write
  pull-requests: write
  
jobs:  
  test-model:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v5
        
      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Install dependencies and run tests
      - run: |
          pip install -r requirements.txt
        
      - name: Run tests
        run: |
          echo "hello" >> report.md
          cat test_output.txt >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
