# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Model Testing 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: iterative/setup-cml@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
        python -m test 2>&1 > test_output.txt
    - name: Create CML report 
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        echo "test_output" >> report.md
        echo "------------" >> report.md
        cat test_output.txt >> report.md
        echo "------------" >> report.md
        cml comment --log debug create --publish report.md
