name: CML
on: [push]
jobs:  
  train-and-report:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v3      
      - run: |
          pip install -r requirements.txt
 
          # Create CML report
          echo "hello" >> report.md
          echo '![](./plot.png "Confusion Matrix")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
